import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import { existsSync, readFileSync } from 'node:fs';

// Per-page last-modified dates, generated by scripts/lastmod.mjs at commit
// time and committed. Keys are paths under src/pages. See that script for why
// this is not computed from git during the build.
const LASTMOD_FILE = new URL('./src/data/lastmod.json', import.meta.url);
const LASTMOD = existsSync(LASTMOD_FILE) ? JSON.parse(readFileSync(LASTMOD_FILE, 'utf8')) : {};

// Map a built URL back to the page file that produced it. Static routes match
// their file directly. Dynamic routes ([city], [trade]) share the date of the
// template that renders them. Anything unresolved gets no lastmod rather than
// a guessed one.
function lastmodFor(url) {
  const path = new URL(url).pathname.replace(/^\/|\/$/g, '');
  const direct = path === '' ? ['index.astro'] : [`${path}.astro`, `${path}/index.astro`];
  for (const candidate of direct) if (LASTMOD[candidate]) return LASTMOD[candidate];

  const parent = path.includes('/') ? path.slice(0, path.lastIndexOf('/')) : '';
  for (const key of Object.keys(LASTMOD)) {
    const dir = key.includes('/') ? key.slice(0, key.lastIndexOf('/')) : '';
    const base = dir ? key.slice(dir.length + 1) : key;
    if (dir === parent && /^\[.+\]\.astro$/.test(base)) return LASTMOD[key];
  }
  return undefined;
}

export default defineConfig({
  site: 'https://www.upkeeppropertymaintenance.com',
  integrations: [
    sitemap({
      serialize(item) {
        const lastmod = lastmodFor(item.url);
        if (lastmod) item.lastmod = lastmod;
        return item;
      },
    }),
  ],
});
